In this Milestone: We completed the task
NickEmma/space-hub pull request #36
Opened 2022-08-24 10:57 UTC by NickEmma

- The Space Travelers' Hub consists of Rockets, Missions, and the My Profile section.
- The Rockets section displays a list of all available SpaceX rockets. Users can book each rocket by clicking the reservation button or canceling the previously made booking.
- The Missions section displays a list of current missions along with their brief description and participation status. 
- There is also a button next to each mission that allows users to join the selected mission or leave the mission the user joined earlier.
- The My Profile section displays all reserved rockets and space missions.

2022-08-24 11:33 UTC, zieeco requested changes
Hi @NickEmma  & @AbdollahRaafat,


Great job so far! 👏 
You've done well, however, there are some issues that you still need to work on to go to the next project, but you are almost there!


## To highlight 🎯

- No linter errors.✔️
- Nice design. ✔️
- Descriptive PR. ✔️


## Required Changes ♻️
_Check the comments under the review._


<img src="https://media0.giphy.com/media/8UGVQESpDMMQl7yd3F/giphy.gif"/>


## Optional suggestions
- N/A

**_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._**


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-24 11:33 UTC, zieeco commented on README.md
> +
- Hey, Team! Great job with the project, however since this is the final project version, then you should add a live demo link or you should not. Leaving it as a broken link is not a good user experience on your readme and it doesn't make you appear professional. please, kindly add a live demo link or remove the section.

2022-08-24 11:33 UTC, zieeco commented on README.md
> +Space Traveler Hub
- Please, kindly replace the `Project Name` with `your project name` here as this is more descriptive instead compared to the way you've implemented it.

2022-08-24 11:33 UTC, zieeco commented on README.md
> +
- Please, kindly re-evaluate this section as it seems vague because users don't get to understand your content well enough. You can choose to make it more descriptive or remove it as it not clear enough to catch the user's attention. please re-evaluate this section.

2022-08-24 11:33 UTC, zieeco commented on README.md
> +
- You've added the command on how to start the app. How can a user install the packages used in building the app? How can the user also run your test files? Please, update this missing part in this section.

2022-08-24 11:33 UTC, zieeco commented on README.md
> +
- Please, kindly add the second author that has contributed to the project as you've both worked in pairs to make your readme more professional.

2022-08-24 11:33 UTC, zieeco commented on README.md
> +thanks:
- Please, kindly update this section by adding the link to the issues page so users can navigate quickly to it to improve the user experience and to make your readme more professional.

2022-08-24 12:28 UTC, NickEmma commented on README.md
> +
done

2022-08-24 12:28 UTC, NickEmma commented on README.md
> +Space Traveler Hub
resolved

2022-08-24 12:28 UTC, NickEmma commented on README.md
> +
noted and resolved

2022-08-24 12:29 UTC, NickEmma commented on README.md
> +
done

2022-08-24 12:29 UTC, NickEmma commented on README.md
> +thanks:
done

2022-08-24 13:39 UTC, EricMbouwe approved these changes
Hi @NickEmma, 

Your project is complete! ⚡🔥  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 🎉🔥
- Requested changes ✔
- Linters ✔
- Styles ✔

## Optional suggestions ☂

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-24 16:42 UTC, merged

2022-10-14 11:15 UTC, NickEmma commented on README.md
> +
@zieeco Thank you for reviewing my project, I will make the necessary  corrections as suggested

2022-10-14 11:16 UTC, NickEmma commented
@EricMbouwe Thank you for reviewing and approving our code.